name: root_finder
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  math_expressions: ^2.6.0
  flutter_math_fork: ^0.7.2
  fl_chart: ^0.65.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  animations: ^2.0.8
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
